#!/usr/bin/env python
# -*- coding: utf-8 -*-


import os
import sys
from tokentype import *
from parser import (Token, Parser)
from objects import (call, type_to_pystr, is_type, args_num, vm)
from objects import (ObjHeader, ClsObj, NilObj, BoolObj, StrObj, IntObj, \
        FloatObj, ListObj, MapObj, ModuleObj, FunObj, Value, Var)


def run_file(argv=None):
    if len(argv) > 1:
        filename = argv[1]
        parser = Parser(filename)
        while True:
            parser.fetch_next_token()
            if parser.cur_token.type == TOKEN_TYPE_EOF:
                print(parser.cur_token)
                return
            print(parser.cur_token)


def main(argv=None):
    person = MapObj({StrObj('name'): StrObj('JH'), StrObj('age'): IntObj(19)})
    person_str = call(person, 'tostr(_)')(person)
    print(person_str.str)

    mymodule = ModuleObj('mymodule')
    mymodule_str = call(mymodule, 'tostr(_)')(mymodule)
    print(mymodule_str.str)

    myfun = FunObj('myfun')
    myfun_str = call(myfun, 'tostr(_)')(myfun)
    print(myfun_str.str)
    

if __name__ == '__main__':
    argv = sys.argv
    main(argv)

