#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
from tokentype import *
from parser import Token, Parser
from objects import *


def main(argv=None):
    """
    if len(argv) > 1:
        filename = argv[1]
        parser = Parser(filename)
        while True:
            parser.fetch_next_token()
            if parser.cur_token.type == TOKEN_TYPE_EOF:
                print(parser.cur_token)
                return
            print(parser.cur_token)
    """
    li = ListObj([IntObj(1), FloatObj(2.5), StrObj('Hello')])
    print(list_to_str(li).str)
    li.obj_header.cls_obj.methods['list_append'](li, StrObj('你好世界'))
    print(list_to_str(li).str)
    call(li, 'list_insert')(li, FloatObj(100.0), IntObj(0))
    print(call(li, 'list_to_str')(li).str)
    print(call(li, 'list_len')(li).int)

if __name__ == '__main__':
    argv = sys.argv
    main(argv)

